### ISSUE TITLE
JDK 7 support for CI builds

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#11]
Can you just compile this with JDK7? It would be nice when using different CI servers that have JDK7 and JDK8.

```
05:31:46 05:31:46 * What went wrong: 05:31:46 A problem occurred evaluating root project 'some-app'. 
05:31:46 > java.lang.UnsupportedClassVersionError: com/vanniktech/android/apk/size/ApkSizePlugin : Unsupported major.minor version 52.0
```

**Comment by vanniktech** [comment]
Closed by #12. Thanks for your contribution :+1:

**Comment by jaredsburrows** [comment]
@vanniktech Can you release this?

https://bintray.com/bintray/jcenter/com.vanniktech%3Agradle-android-apk-size-plugin/view

**Comment by vanniktech** [comment]
@jaredsburrows 
I just published the new version to maven central. It should be available soon
