### ISSUE TITLE
Use Spock for Testing

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#40]
Site: http://spockframework.org/

Example: https://github.com/gradle/gradle/blob/master/subprojects/core/src/test/groovy/org/gradle/api/file/FileCollectionSymlinkTest.groovy

**Comment by vanniktech** [comment]
Would make sense and could also improve tests

**Comment by jaredsburrows** [comment]
I can make a PR for this.

**Comment by vanniktech** [comment]
Sure go for it !
