### ISSUE TITLE
Show Megabytes next to bytes for command line print out

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#41]
Line: https://github.com/vanniktech/gradle-android-apk-size-plugin/blob/master/src/main/groovy/com/vanniktech/android/apk/size/ApkSizeTask.groovy#L23

`out.warn("Total ${fileEnding} Size in ${apk.name} in bytes: ${apkSizeBytes} (${apkSizeMegaBytes})")`

**Comment by vanniktech** [comment]
Definitely useful if you want hit up a PR we might even want to round it to two digits (e.g. 1,89mb)
