### ISSUE TITLE
Use Coveralls instead of CodeCov

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#46]
https://coveralls.io/ and example: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/README.md

**Comment by vanniktech** [comment]
I don't necessarily feel like migrating a bunch of projects to coveralls. I also tried it earlier when I chose to go with codecov and I never got it working.

Why do you want to change?

**Comment by jaredsburrows** [comment]
We can remove the extra configuration file: https://github.com/vanniktech/gradle-android-apk-size-plugin/blob/master/codecov.yml.

Coveralls is extremely easy to setup and use: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/gradle/quality.gradle#L8.

**Comment by vanniktech** [comment]
For now, I won't change it. It works more or less right now.

**Comment by jaredsburrows** [comment]
Sounds good. Thanks for considering!
