### ISSUE TITLE
[Feature Request] Fail build on "maxApkSize"

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#48]
## Question:
Can we add an integer such as "maxApkSize" in an extension in order to fail builds that go over a certain size?

## Example:
```
apkSize {
  maxApkSize = 5800000
}
```

This will help developers that are developing on their local machines not only make better decisions on the code that they write but the libraries they use.

**Comment by vanniktech** [comment]
That seems like a really good idea. 👍

**Comment by vanniktech** [comment]
If so it should be splitted though usually debug apk is much bigger than release.

**Comment by athkalia** [comment]
@vanniktech I am trying to set a limit only for my release build, is this possible?

**Comment by vanniktech** [comment]
I don't think so. The release hasn't been made. You can try the snapshot though.

**Comment by athkalia** [comment]
Sorry for the confusion. I mean in the snapshot version 0.4-SNAPSHOT, is there a way to only fail my build (assembleRelease) if the size of the release apk is too large, but not have any rules around sizes for my debug APK?

**Comment by vanniktech** [comment]
Oh no. There's only one size unfortunately.

**Comment by athkalia** [comment]
would be cool if you could add that in. as, as you said, the release apk is usually smaller cause of proguard

**Comment by vanniktech** [comment]
Yeah. If you want you can create a PR for it. I don't have much time to work on this project at the moment.

**Comment by athkalia** [comment]
I may attempt it, but I've never touched a gradle plugin. Got any suggestions for how to solve this?

**Comment by vanniktech** [comment]
You can look at the PR that did the initial implementation.

**Comment by jaredsburrows** [comment]
@athkalia  Use gradle:

```
gradle.taskGraph.afterTask { task ->
    if (gradle.taskGraph.hasTask("assembleRelease")) {
        dexcount {
            maxApkSize = 5800000
        }
    }
}
```

**Comment by jaredsburrows** [comment]
@athkalia  Use gradle:

```
gradle.taskGraph.afterTask { task ->
    if (gradle.taskGraph.hasTask("assembleRelease")) {
        dexcount {
            maxApkSize = 5800000
        }
    }
}
```

**Comment by athkalia** [comment]
the task graph is always going to have an assembleRelease task right? regardless of which task is currently executing, assembleDebug or assembleRelease

**Comment by jaredsburrows** [comment]
@athkalia No and I didn't mean to use `afterTask`.

Something like this:

```
gradle.taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(":app:assembleRelease")) {
        dexcount {
            maxApkSize = 5800000
        }
    }
}
```

To set `dexcount.maxApkSize = 5800000`, simply run:

```
gradlew :app:assembleRelease
```

Docs: https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#configure-by-dag

**Comment by athkalia** [comment]
thanks pal, I'll give it a go

**Comment by athkalia** [comment]
cool pal, it works!! thanks a lot.

Btw it should be ```apkSize``` instead of ```dexcount ```

**Comment by jaredsburrows** [comment]
@vanniktech It looks like we need to fix the README.md: https://github.com/vanniktech/gradle-android-apk-size-plugin#configuration.

**Comment by athkalia** [comment]
I also noticed that in the console this appears btw

```The current APK is 2853469 Kb, the current max is: 1 Kb.```
It should have been bytes not Kb

**Comment by jaredsburrows** [comment]
@athkalia @vanniktech Should we create an issue for this?

**Comment by vanniktech** [comment]
Sure.
