### ISSUE TITLE
gradle sizeDebugApk - Android Gradle Plugin 1.5.0

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#5]
This fails with the following:

```
$ gradle sizeDebugApk
$ gradle assemble sizeDebugApk
```

Error Message:

```
:sizeDebugApk

FAILURE: Build failed with an exception.

* What went wrong:
Could not add entry ':sizeDebugApk' to cache taskArtifacts.bin (~/.gradle/2.8/taskArtifacts/taskArtifacts.bin).
> Unable to store task input properties. Property 'apk' with value 'com.android.build.gradle.internal.api.ApkVariantOutputImpl_Decorated@122800df' cannot be serialized.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.79 secs
```

**Comment by vanniktech** [comment]
As far as I know `gradle sizeDebugApk` fails if there is no APK file. `gradle assemble sizeDebugApk` should work though since it does build the apk.

Can you verify that?

If that's the case, I'd propose a custom message instead of crashing when there is no APK file.

**Comment by vanniktech** [comment]
Okay I was able to reproduce this one. Though I have the same problem when I'm using the dexcount. Can you execute `count<Variant>DexMethods` without getting any errors?

**Comment by vanniktech** [comment]
@jaredsburrows I'll release 0.1.1 later this day and also work on #3 in the next few days

**Comment by jaredsburrows** [comment]
@vanniktech Sounds good! I am looking forward to it.

**Comment by vanniktech** [comment]
@jaredsburrows I just published the new version to Maven Central and to Gradle Plugins

**Comment by vanniktech** [comment]
@jaredsburrows automated snapshots are now also working

**Comment by jaredsburrows** [comment]
@vanniktech Nice Job!

```
:app:root-checker:packageDebug
:app:root-checker:zipalignDebug
:app:root-checker:assembleDebug
Total methods in root-checker-debug.apk: 38083
Total fields in root-checker-debug.apk:  21817
Total APK Size in root-checker-debug.apk in bytes: 3231060 <--- Your plugin

BUILD SUCCESSFUL
```

**Comment by vanniktech** [comment]
Thanks. If you run into any issues, let me know. I also updated the README and added some more information.
