### ISSUE TITLE
Move Gradle plugin to Kotlin?

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#56]
@vanniktech What do you think?
main source - Kotlin
test source - Groovy + Spock

**Comment by vanniktech** [comment]
We could even do kotlin in tests. I'd like it very much.

**Comment by jaredsburrows** [comment]
I would like to start the conversion soon.

**Comment by vanniktech** [comment]
Go for it :)

**Comment by vanniktech** [comment]
Feel free to do it but I don't feel like having this issue hanging here.

**Comment by jaredsburrows** [comment]
Now I feel like I should do this now.

**Comment by vanniktech** [comment]
Didn't mean you to do it but if closing this issue boosted your motivation to do this it's even better :D

**Comment by jaredsburrows** [comment]
@vanniktech Sure. Let me look into it.
