### ISSUE TITLE
[Feature Request] - Do not run the count on each build

### ISSUE THREAD

**Issue by jaredsburrows** [vanniktech/gradle-android-apk-size-plugin#67]
Add an option to the plugin's extension to prevent it from counting after each `assembleDebug`.

**Comment by vanniktech** [comment]
What's the use case for this? I also saw that you posted this on the dexcount plugin

**Comment by jaredsburrows** [comment]
I run `gradlew assembleDebug installDebug runDebug`. I do not need the dex count plugin and the apk plugin to count after each run.

**Comment by vanniktech** [comment]
What I do is that I only apply the plugin when I'm on the CI.

**Comment by jaredsburrows** [comment]
Yeah, I have flags now. Maybe this is not such a big deal. Just a request/suggestion.

**Comment by vanniktech** [comment]
Basically I've got:

```groovy
def isOnCI() {
  project.hasProperty('isCI')
}

if (isOnCI()) {
  apply plugin: 'com.vanniktech.android.apk.size'
}
```

and then on CI I do `./gradlew -PisCI clean build` and then I want to know the apk size locally I just use the `-PisCI`.

**Comment by jaredsburrows** [comment]
Yes, I use properties as well. I was just making a suggestion.
